import { Client } from 'pg';

export async function createCourses(client: Client) {
  await client.query(`
        CREATE TABLE IF NOT EXISTS courses (
            id SERIAL PRIMARY KEY,
            course_name VARCHAR(400)
        );
    `);

    await client.query(`
        INSERT INTO courses (course_name) VALUES
        ('BA In Anthropology'),
        ('BA In Broadcasting'),
        ('BA In Communication'),
        ('BA In Economics'),
        ('BA In English'),
        ('BA In Filipino'),
        ('BA In History'),
        ('BA In Islamic Studies'),
        ('BA In Journalism'),
        ('BA In Linguistics'),
        ('BA In Literature'),
        ('BA In Mass Communication'),
        ('BA In Philosophy'),
        ('BA In Political Science'),
        ('BA In Psychology'),
        ('BA In Sociology'),
        ('Beed In Elementary Education'),
        ('Beed In Elementary Education Major In Preschool Education'),
        ('Beed In Elementary Education Major In Special Education'),
        ('Bfa In Industrial Design'),
        ('Bfa In Painting'),
        ('Bfa In Sculpture'),
        ('Bfa In Visual Communication'),
        ('Bla In Landscape Architecture'),
        ('Blis In Library And Information Science'),
        ('Bpa In Public Administration'),
        ('Bpe In Physical Education'),
        ('BS In Accountancy'),
        ('BS In Accounting Technology'),
        ('BS In Aeronautical Engineering'),
        ('BS In Agribusiness'),
        ('BS In Agriculture'),
        ('BS In Agroforestry'),
        ('BS In Applied Mathematics'),
        ('BS In Applied Physics'),
        ('BS In Architecture'),
        ('BS In Biology'),
        ('BS In Business Administration'),
        ('BS In Business Administration Major In Business Economics'),
        ('BS In Business Administration Major In Financial Management'),
        ('BS In Business Administration Major In Human Resource Development'),
        ('BS In Business Administration Major In Marketing Management'),
        ('BS In Business Administration Major In Operations Management'),
        ('BS In Ceramic Engineering'),
        ('BS In Chemical Engineering'),
        ('BS In Chemistry'),
        ('BS In Civil Engineering'),
        ('BS In Community Development'),
        ('BS In Computer Engineering'),
        ('BS In Computer Science'),
        ('BS In Criminology'),
        ('BS In Customs Administration'),
        ('BS In Development Communication'),
        ('BS In Economics'),
        ('BS In Electrical Engineering'),
        ('BS In Electronics Engineering'),
        ('BS In Entrepreneurship'),
        ('BS In Environmental Science'),
        ('BS In Fisheries'),
        ('BS In Food Technology'),
        ('BS In Foreign Service'),
        ('BS In Forensic Science'),
        ('BS In Forestry'),
        ('BS In Geodetic Engineering'),
        ('BS In Geological Engineering'),
        ('BS In Geology'),
        ('BS In Hotel And Restaurant Management'),
        ('BS In Industrial Engineering'),
        ('BS In Information Systems'),
        ('BS In Information Technology'),
        ('BS In Interior Design'),
        ('BS In International Studies'),
        ('BS In Marine Engineering'),
        ('BS In Marine Transportation'),
        ('BS In Materials Engineering'),
        ('BS In Mathematics'),
        ('BS In Mechanical Engineering'),
        ('BS In Medical Technology'),
        ('BS In Metallurgical Engineering'),
        ('BS In Midwifery'),
        ('BS In Mining Engineering'),
        ('BS In Molecular Biology'),
        ('BS In Nursing'),
        ('BS In Nutrition And Dietetics'),
        ('BS In Occupational Therapy'),
        ('BS In Office Administration'),
        ('BS In Petroleum Engineering'),
        ('BS In Pharmacy'),
        ('BS In Physical Therapy'),
        ('BS In Physics'),
        ('BS In Psychology'),
        ('BS In Public Safety'),
        ('BS In Radiologic Technology'),
        ('BS In Real Estate Management'),
        ('BS In Respiratory Therapy'),
        ('BS In Sanitary Engineering'),
        ('BS In Social Work'),
        ('BS In Speech-Language Pathology'),
        ('BS In Sports Science'),
        ('BS In Statistics'),
        ('BS In Tourism Management'),
        ('Bsed In Secondary Education'),
        ('Bsed In Secondary Education Major In Biological Sciences'),
        ('Bsed In Secondary Education Major In English'),
        ('Bsed In Secondary Education Major In Filipino'),
        ('Bsed In Secondary Education Major In Islamic Studies'),
        ('Bsed In Secondary Education Major In Mathematics'),
        ('Bsed In Secondary Education Major In Music, Arts, Physical And Health Education'),
        ('Bsed In Secondary Education Major In Physical Sciences'),
        ('Bsed In Secondary Education Major In Social Studies'),
        ('Bsed In Secondary Education Major In Technology And Livelihood Education'),
        ('Bsed In Secondary Education Major In Values Education');
    `);
}
