name: Build Verification

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name:  ${{ matrix.label }} Build
        runs-on: ubuntu-latest
        strategy: 
            fail-fast: false
            matrix:
                include:
                    - label: Backend NTC Internship Portal
                      workdir: server
                      lint: true
                      test: true
        defaults:
            run:
                working-directory: ${{ matrix.workdir }}
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                   node-version: 20
                   cache: npm
                   cache-dependency-path: ${{ matrix.workdir }}/package-lock.json

            - name: Installing Dependencies
              run: npm ci

            - name: Lint Checking
              if: matrix.lint == true
              run: npm run lint

            - name: Test
              if: matrix.test == true
              run: npm run test
            
            - name: Build
              run: npm run build