name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

# ADD THESE THREE LINES:
permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: Yurei21
          name: ojt-portal
          base: master
          head: master
          token: ${{ secrets.MY_PAT }} 
