name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          token: ${{ github.token }}
          owner: Yurei21
          repo: ojt-portal
          base: master
          head: master
